import { UniversalModuleContract } from '../../core/contracts/ModuleContract';

export const ResearchInnovationGovernanceModule: UniversalModuleContract = {
  moduleId: 'mod_research_innovation_governance',
  name: 'Institutional Research, IP, Grants & Commercialization Governance Engine',
  displayName: 'Research & IP Governance',
  description: 'Authoritative governance for research portfolios, projects, grant awards, IP disclosures, tech transfer, and commercialization pipelines.',
  version: '1.0.0',
  status: 'INSTALLED',
  category: 'Operations',
  provider: 'EduTech-SMS',
  dependencies: [],
  configurationSchema: [],
  navigationItems: [],
  permissions: [
    { code: 'research.view', name: 'View Research Governance', description: 'View governed research portfolios, projects, and outputs.' },
    { code: 'research.create', name: 'Create Research Proposals', description: 'Create draft research proposals and projects.' },
    { code: 'research.edit', name: 'Edit Research Projects', description: 'Edit existing research projects and proposals.' },
    { code: 'research.manage', name: 'Manage Research Governance', description: 'Manage overall research governance settings and policies.' },
    { code: 'research.portfolio.manage', name: 'Manage Portfolios', description: 'Manage strategic research portfolios.' },
    { code: 'research.program.manage', name: 'Manage Programs', description: 'Manage research programs.' },
    { code: 'research.project.manage', name: 'Manage Projects', description: 'Manage research project lifecycles.' },
    { code: 'research.opportunity.view', name: 'View Opportunities', description: 'View research and funding opportunities.' },
    { code: 'research.opportunity.manage', name: 'Manage Opportunities', description: 'Manage funding opportunities.' },
    { code: 'research.grant.view', name: 'View Grants', description: 'View grant applications and awards.' },
    { code: 'research.grant.manage', name: 'Manage Grants', description: 'Manage grant applications.' },
    { code: 'research.grant.submit', name: 'Submit Grants', description: 'Submit grant applications.' },
    { code: 'research.grant.approve', name: 'Approve Grants', description: 'Approve grant applications.' },
    { code: 'research.proposal.manage', name: 'Manage Proposals', description: 'Manage research proposals.' },
    { code: 'research.proposal.review', name: 'Review Proposals', description: 'Review research proposals.' },
    { code: 'research.proposal.approve', name: 'Approve Proposals', description: 'Approve research proposals.' },
    { code: 'research.team.manage', name: 'Manage Research Teams', description: 'Manage research investigators and teams.' },
    { code: 'research.milestone.manage', name: 'Manage Milestones', description: 'Manage research milestones.' },
    { code: 'research.deliverable.manage', name: 'Manage Deliverables', description: 'Manage research deliverables.' },
    { code: 'research.output.manage', name: 'Manage Research Outputs', description: 'Manage research outputs and datasets.' },
    { code: 'research.publication.manage', name: 'Manage Publications', description: 'Manage research publications.' },
    { code: 'research.agreement.view', name: 'View Agreements', description: 'View research agreements.' },
    { code: 'research.agreement.manage', name: 'Manage Agreements', description: 'Manage sponsored and industry research agreements.' },
    { code: 'research.ip.view', name: 'View IP', description: 'View intellectual property disclosures and records.' },
    { code: 'research.ip.manage', name: 'Manage IP Disclosures', description: 'Manage IP disclosures.' },
    { code: 'research.ip.assess', name: 'Assess IP', description: 'Perform technical and commercial IP assessments.' },
    { code: 'research.ip.protect', name: 'Approve IP Protection', description: 'Approve patent, copyright, or trademark protection.' },
    { code: 'research.patent.manage', name: 'Manage Patents', description: 'Manage patent records.' },
    { code: 'research.copyright.manage', name: 'Manage Copyrights', description: 'Manage copyright records.' },
    { code: 'research.trademark.manage', name: 'Manage Trademarks', description: 'Manage trademark records.' },
    { code: 'research.transfer.manage', name: 'Manage Tech Transfer', description: 'Manage technology transfer opportunities.' },
    { code: 'research.commercialization.manage', name: 'Manage Commercialization', description: 'Manage commercialization pipelines.' },
    { code: 'research.license.manage', name: 'Manage Licenses', description: 'Manage IP licensing records.' },
    { code: 'research.innovation.manage', name: 'Manage Innovation', description: 'Manage innovation pipeline records.' },
    { code: 'research.innovation.advance', name: 'Advance Innovation', description: 'Advance innovation pipeline stages.' },
    { code: 'research.ethics.view', name: 'View Research Ethics', description: 'View research ethics approvals.' },
    { code: 'research.ethics.manage', name: 'Manage Research Ethics', description: 'Manage research ethics references.' },
    { code: 'research.compliance.view', name: 'View Research Compliance', description: 'View research compliance records.' },
    { code: 'research.compliance.manage', name: 'Manage Research Compliance', description: 'Manage research compliance records.' },
    { code: 'research.coi.manage', name: 'Manage COI Disclosures', description: 'Manage research conflict of interest disclosures.' },
    { code: 'research.coi.review', name: 'Review COI Disclosures', description: 'Review research conflict of interest disclosures.' },
    { code: 'research.reporting.manage', name: 'Manage Grant Reporting', description: 'Manage grant reporting obligations.' },
    { code: 'research.risk.manage', name: 'Manage Research Risks', description: 'Manage research risks.' },
    { code: 'research.exception.manage', name: 'Manage Research Exceptions', description: 'Manage research exceptions.' },
    { code: 'research.benefit.manage', name: 'Manage Research Benefits', description: 'Manage research benefit targets.' },
    { code: 'research.impact.manage', name: 'Manage Research Impact', description: 'Manage research impact records.' },
    { code: 'research.diagnostics.run', name: 'Run Research Diagnostics', description: 'Execute research governance diagnostics.' },
    { code: 'research.audit.view', name: 'View Research Audit', description: 'View research governance audit logs.' }
  ]
};
