import { UniversalModuleContract } from '../../core/contracts/ModuleContract';

export const KnowledgeGovernanceModule: UniversalModuleContract = {
  moduleId: 'mod_knowledge_governance',
  name: 'Institutional & Organizational Knowledge Governance Engine',
  displayName: 'Knowledge Governance',
  description: 'Authoritative governance for institutional knowledge repositories, articles, practices, lessons, expertise, and organizational memory.',
  version: '1.0.0',
  status: 'INSTALLED',
  category: 'Operations',
  provider: 'EduTech-SMS',
  dependencies: [],
  configurationSchema: [],
  navigationItems: [],
  permissions: [
    { code: 'knowledge.view', name: 'View Knowledge', description: 'View governed institutional knowledge assets.' },
    { code: 'knowledge.create', name: 'Create Knowledge', description: 'Create draft knowledge assets.' },
    { code: 'knowledge.edit', name: 'Edit Knowledge', description: 'Edit existing knowledge drafts.' },
    { code: 'knowledge.manage', name: 'Manage Knowledge', description: 'Manage knowledge governance settings.' },
    { code: 'knowledge.domain.manage', name: 'Manage Knowledge Domains', description: 'Manage knowledge domains.' },
    { code: 'knowledge.asset.manage', name: 'Manage Knowledge Assets', description: 'Manage knowledge assets.' },
    { code: 'knowledge.article.view', name: 'View Articles', description: 'View knowledge articles.' },
    { code: 'knowledge.article.manage', name: 'Manage Articles', description: 'Manage knowledge articles.' },
    { code: 'knowledge.article.publish', name: 'Publish Articles', description: 'Publish knowledge articles.' },
    { code: 'knowledge.collection.manage', name: 'Manage Collections', description: 'Manage knowledge collections.' },
    { code: 'knowledge.taxonomy.manage', name: 'Manage Taxonomy', description: 'Manage knowledge taxonomy.' },
    { code: 'knowledge.tag.manage', name: 'Manage Tags', description: 'Manage knowledge tags.' },
    { code: 'knowledge.reference.manage', name: 'Manage References', description: 'Manage knowledge references.' },
    { code: 'knowledge.evidence.manage', name: 'Manage Evidence', description: 'Manage knowledge evidence.' },
    { code: 'knowledge.practice.manage', name: 'Manage Practices', description: 'Manage institutional practices.' },
    { code: 'knowledge.lesson.manage', name: 'Manage Lessons', description: 'Manage lessons learned.' },
    { code: 'knowledge.lesson.validate', name: 'Validate Lessons', description: 'Validate lessons learned.' },
    { code: 'knowledge.memory.manage', name: 'Manage Memory', description: 'Manage organizational memory records.' },
    { code: 'knowledge.expertise.view', name: 'View Expertise', description: 'View expertise profiles.' },
    { code: 'knowledge.expertise.manage', name: 'Manage Expertise', description: 'Manage expertise profiles.' },
    { code: 'knowledge.expertise.certify', name: 'Certify Expertise', description: 'Certify expertise profiles.' },
    { code: 'knowledge.research.view', name: 'View Research Knowledge', description: 'View research knowledge.' },
    { code: 'knowledge.research.manage', name: 'Manage Research Knowledge', description: 'Manage research knowledge.' },
    { code: 'knowledge.learning.view', name: 'View Learning Resources', description: 'View learning resources.' },
    { code: 'knowledge.learning.manage', name: 'Manage Learning Resources', description: 'Manage learning resources.' },
    { code: 'knowledge.question.manage', name: 'Manage Questions', description: 'Manage knowledge questions.' },
    { code: 'knowledge.answer.manage', name: 'Manage Answers', description: 'Manage knowledge answers.' },
    { code: 'knowledge.answer.review', name: 'Review Answers', description: 'Review knowledge answers.' },
    { code: 'knowledge.review.manage', name: 'Manage Reviews', description: 'Manage knowledge reviews.' },
    { code: 'knowledge.certification.manage', name: 'Manage Certification', description: 'Manage knowledge certifications.' },
    { code: 'knowledge.search', name: 'Search Knowledge', description: 'Perform governed knowledge search.' },
    { code: 'knowledge.lineage.view', name: 'View Lineage', description: 'View knowledge lineage.' },
    { code: 'knowledge.lineage.manage', name: 'Manage Lineage', description: 'Manage knowledge lineage.' },
    { code: 'knowledge.gap.manage', name: 'Manage Gaps', description: 'Manage knowledge gaps.' },
    { code: 'knowledge.risk.manage', name: 'Manage Risk', description: 'Manage knowledge risks.' },
    { code: 'knowledge.exception.manage', name: 'Manage Exceptions', description: 'Manage knowledge exceptions.' },
    { code: 'knowledge.audit.view', name: 'View Audit Logs', description: 'View knowledge governance audit logs.' },
    { code: 'knowledge.restricted_view', name: 'View Restricted Knowledge', description: 'View restricted-classification knowledge assets.' }
  ]
};
