import { UniversalModuleContract } from '../../core/contracts/ModuleContract';

export const DataGovernanceModule: UniversalModuleContract = {
  moduleId: 'mod_data_governance',
  name: 'Institutional Data Governance & Quality',
  displayName: 'Data Governance',
  description: 'Enterprise master data, quality, lineage, and data stewardship engine.',
  version: '1.0.0',
  status: 'INSTALLED',
  category: 'Operations',
  provider: 'EduTech-SMS',
  dependencies: [],
  configurationSchema: [],
  navigationItems: [],
  permissions: [
    { code: 'data.view', name: 'View Data', description: 'View governed data assets.' },
    { code: 'data.create', name: 'Create Data Asset', description: 'Create data assets.' },
    { code: 'data.edit', name: 'Edit Data Asset', description: 'Edit data assets.' },
    { code: 'data.manage', name: 'Manage Data', description: 'Manage data governance settings.' },
    { code: 'data.domain.manage', name: 'Manage Domains', description: 'Manage data domains.' },
    { code: 'data.asset.manage', name: 'Manage Assets', description: 'Manage data assets.' },
    { code: 'data.owner.manage', name: 'Manage Owners', description: 'Manage data owners.' },
    { code: 'data.steward.manage', name: 'Manage Stewards', description: 'Manage data stewards.' },
    { code: 'data.dictionary.manage', name: 'Manage Dictionary', description: 'Manage data dictionary entries.' },
    { code: 'data.glossary.manage', name: 'Manage Glossary', description: 'Manage business glossary.' },
    { code: 'data.metadata.manage', name: 'Manage Metadata', description: 'Manage metadata definitions.' },
    { code: 'data.lineage.view', name: 'View Lineage', description: 'View data lineage.' },
    { code: 'data.lineage.manage', name: 'Manage Lineage', description: 'Manage data lineage records.' },
    { code: 'data.master.manage', name: 'Manage Master Data', description: 'Manage master data records.' },
    { code: 'data.reference.manage', name: 'Manage Reference Data', description: 'Manage reference data sets.' },
    { code: 'data.quality.view', name: 'View Quality', description: 'View data quality rules and issues.' },
    { code: 'data.quality.manage', name: 'Manage Quality', description: 'Manage data quality configuration.' },
    { code: 'data.quality.execute', name: 'Execute Quality', description: 'Execute data quality rules.' },
    { code: 'data.exception.manage', name: 'Manage Exceptions', description: 'Manage data quality exceptions.' },
    { code: 'data.remediation.manage', name: 'Manage Remediation', description: 'Manage data remediation actions.' },
    { code: 'data.certification.manage', name: 'Manage Certification', description: 'Manage data certifications.' },
    { code: 'data.contract.manage', name: 'Manage Contracts', description: 'Manage data contracts.' },
    { code: 'data.standard.manage', name: 'Manage Standards', description: 'Manage data standards.' },
    { code: 'data.sharing.manage', name: 'Manage Sharing', description: 'Manage data sharing agreements.' },
    { code: 'data.access.manage', name: 'Manage Access', description: 'Manage data access policies.' },
    { code: 'data.provenance.view', name: 'View Provenance', description: 'View data provenance records.' },
    { code: 'data.risk.manage', name: 'Manage Risk', description: 'Manage data risks.' },
    { code: 'data.governance_decision.manage', name: 'Manage Decisions', description: 'Manage governance decisions.' },
    { code: 'data.audit.view', name: 'View Audit', description: 'View data governance audit logs.' }
  ]
};
