import { UniversalModuleContract } from '../../core/contracts/ModuleContract';

export const HumanCapitalGovernanceModule: UniversalModuleContract = {
  moduleId: 'mod_human_capital_governance',
  name: 'Institutional Human Capital, Workforce, Talent & Performance Governance Engine',
  displayName: 'Human Capital & Workforce',
  description: 'Authoritative governance for workforce strategy, capacity planning, competency frameworks, talent pools, performance cycles, succession planning, and organizational capability.',
  version: '1.0.0',
  status: 'INSTALLED',
  category: 'Operations',
  provider: 'EduTech-SMS',
  dependencies: [],
  configurationSchema: [],
  navigationItems: [],
  permissions: [
    { code: 'human_capital.view', name: 'View Human Capital Governance', description: 'View workforce governance dashboards and records.' },
    { code: 'human_capital.create', name: 'Create Workforce Records', description: 'Create workforce strategy, goal, and scenario records.' },
    { code: 'human_capital.edit', name: 'Edit Workforce Records', description: 'Edit existing human capital governance records.' },
    { code: 'human_capital.manage', name: 'Manage Human Capital', description: 'Manage overall human capital governance settings.' },
    { code: 'human_capital.workforce.manage', name: 'Manage Workforce Strategy', description: 'Manage strategic workforce plans and scenarios.' },
    { code: 'human_capital.position.manage', name: 'Manage Position Governance', description: 'Manage position criticality and dependency governance.' },
    { code: 'human_capital.role.manage', name: 'Manage Role Governance', description: 'Manage role sensitivity and competency requirements.' },
    { code: 'human_capital.competency.manage', name: 'Manage Competency Frameworks', description: 'Manage institutional competency frameworks.' },
    { code: 'human_capital.skill.manage', name: 'Manage Skills', description: 'Manage skill definitions and verification.' },
    { code: 'human_capital.talent.view', name: 'View Talent Governance', description: 'View talent pools and assessments.' },
    { code: 'human_capital.talent.manage', name: 'Manage Talent Pools', description: 'Manage talent pools and candidate nominations.' },
    { code: 'human_capital.talent.assess', name: 'Assess Talent', description: 'Perform talent potential and performance assessments.' },
    { code: 'human_capital.career.manage', name: 'Manage Career Development', description: 'Manage career pathways and development plans.' },
    { code: 'human_capital.development.manage', name: 'Manage Development Plans', description: 'Manage individual development objectives.' },
    { code: 'human_capital.training.manage', name: 'Manage Training Governance', description: 'Manage mandatory and role-required training governance.' },
    { code: 'human_capital.performance.view', name: 'View Performance', description: 'View performance cycle metrics and reviews.' },
    { code: 'human_capital.performance.manage', name: 'Manage Performance Cycles', description: 'Manage performance cycles and KRAs/KPIs.' },
    { code: 'human_capital.performance.review', name: 'Conduct Performance Review', description: 'Conduct and submit employee performance reviews.' },
    { code: 'human_capital.performance.approve', name: 'Approve Performance Reviews', description: 'Approve performance reviews.' },
    { code: 'human_capital.performance.calibrate', name: 'Calibrate Performance', description: 'Perform performance calibration adjustments.' },
    { code: 'human_capital.recognition.manage', name: 'Manage Recognition', description: 'Manage institutional recognition and awards.' },
    { code: 'human_capital.succession.view', name: 'View Succession Plans', description: 'View succession plans and critical role coverage.' },
    { code: 'human_capital.succession.manage', name: 'Manage Succession Plans', description: 'Manage succession candidates and readiness.' },
    { code: 'human_capital.succession.approve', name: 'Approve Succession Nominations', description: 'Approve succession candidate nominations.' },
    { code: 'human_capital.promotion.manage', name: 'Manage Promotion Governance', description: 'Manage promotion proposals.' },
    { code: 'human_capital.promotion.approve', name: 'Approve Promotions', description: 'Approve promotion governance proposals.' },
    { code: 'human_capital.tenure.view', name: 'View Tenure References', description: 'View tenure governance references.' },
    { code: 'human_capital.tenure.manage', name: 'Manage Tenure References', description: 'Manage tenure milestones and reviews.' },
    { code: 'human_capital.tenure.approve', name: 'Approve Tenure Decisions', description: 'Approve institutional tenure decisions.' },
    { code: 'human_capital.pip.manage', name: 'Manage PIPs', description: 'Manage performance improvement plans.' },
    { code: 'human_capital.engagement.view', name: 'View Engagement Metrics', description: 'View aggregate employee engagement observations.' },
    { code: 'human_capital.risk.manage', name: 'Manage Workforce Risks', description: 'Manage workforce risk mitigation.' },
    { code: 'human_capital.retention.manage', name: 'Manage Retention Risks', description: 'Manage key talent retention risks.' },
    { code: 'human_capital.capability.manage', name: 'Manage Organizational Capability', description: 'Manage organizational capability assessments.' },
    { code: 'human_capital.resilience.manage', name: 'Manage Workforce Resilience', description: 'Manage workforce resilience assessments.' },
    { code: 'human_capital.knowledge_transfer.manage', name: 'Manage Knowledge Transfer', description: 'Manage knowledge transfer plans during transitions.' },
    { code: 'human_capital.offboarding.manage', name: 'Manage Offboarding Governance', description: 'Manage offboarding continuity governance.' },
    { code: 'human_capital.exception.manage', name: 'Manage Exceptions', description: 'Manage human capital policy exceptions.' },
    { code: 'human_capital.exception.approve', name: 'Approve Exceptions', description: 'Approve human capital policy exceptions.' },
    { code: 'human_capital.diagnostics.run', name: 'Run HC Diagnostics', description: 'Execute human capital governance diagnostics.' },
    { code: 'human_capital.audit.view', name: 'View HC Audit', description: 'View human capital governance audit logs.' }
  ]
};
